config/routes.rb
WizardingRegistry::Application.routes.draw do

  devise_for :users do
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end

  devise_for :users , :controllers => { :registrations => "registrations" }

  match '/user' => "home#index", :as => "/"

  resources :users

  get "search/index", :as => "search"
  get "/about"  => "home#about"
  get "/contact" => "home#contact"

  match ":name" => "users#show"
 
  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :real_name, :email, :password, :password_confirmation, :remember_me
  attr_accessible :name, :bio, :tumblr, :twitter, :facebook, :skype, :aim, :site, :site2, :youtube, :google_plus
  attr_accessible :pet, :house, :house_points
  attr_accessible :wand_tree, :wand_length, :wand_core, :wand_spec

  # validates_uniqueness_of :name, :email, :tumblr, :facebook, :twitter, :real_name
  validates_presence_of   :name, :email
  validates_length_of     :name, :minimum => 6

  # searchable do  #Sunspot helpers... not useable on heroku :(
  #   text :name, :email, :twitter, :facebook, :tumblr, :real_name
  # end


  def to_param
    name
  end
  
  def update_with_password(params={})
    params.delete(:current_password)
    self.update_without_password(params)
  end

  def self.search(search)
    if search
      query = "%#{search}%"
      results = where('name      LIKE ? OR
                       email     LIKE ? OR
                       tumblr    LIKE ? OR
                       twitter   LIKE ? OR
                       facebook  LIKE ? OR
                       real_name LIKE ?', query, query, query, query, query, query)
      return results
    else
      scoped
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	@user = User.new
  end

  def about
  	@users ||= User.all.count
  end

  def contact
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def update
    # Override Devise to use update_attributes instead of update_with_password.
    # This is the only change we make.
    if resource.update_attributes(params[resource_name])
      set_flash_message :notice, :updated
      # Line below required if using Devise >= 1.2.0
      sign_in resource_name, resource, :bypass => true
      redirect_to after_update_path_for(resource)
    else
      clean_up_passwords(resource)
      render_with_scope :edit
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
	@search = User.search(params[:search])
	@user = @search.first
	if @user == [] or @user == nil
  		redirect_to :back, :alert => "Wizard not Found"
  	else 
  		redirect_to @user
  	end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    # @search = User.search { fulltext params[:search] } #Sunspot Gem Call ; Not useable on heroku
    # @users = @search.results
    @search = User.search(params[:search])
   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @query = User.where(:name => (params[:name] || params[:id]))
    @user = @query.first
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @query = User.where(:name => (params[:name] || params[:id]))

    @user = @query.first
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    params[:user].delete(:password) if params[:user][:password].blank?
    @query = User.where(:name => (params[:name] || params[:id]))
    @user = @query.first
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @query = User.where(:name => (params[:name] || params[:id]))
    @user = @query.first
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def present(object, klass = nil)
    klass ||= "#{object.class}Presenter".constantize
    presenter = klass.new(object, self)
    yield presenter if block_given?
    presenter
  end


  def current_url(overwrite={})
    url_for :only_path => false, :params => params.merge(overwrite)
  end

  def has_permission?
    if current_user
      if current_user.id == @user.id
        true
      else
        false
      end
    else
      false
    end
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_share.html.erb
<div id="share">
  
  <h2>Spread The Word</h2>
  
  <hr>

  <div id="facebook">
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {return;}
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#appId=268713063150612&xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <div class="fb-like" data-send="false" data-layout="box_count" data-width="50" data-show-faces="false"></div>
  </div>

  <div id="twitter">
    <a href="https://twitter.com/share" class="twitter-share-button" data-text="Looking for someone on pottermore? Find them on Wizarding Registry!" data-count="vertical" data-via="WizardRegistry" data-related="JAH2488">Tweet!</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
  </div>

  <div class="clearfix"></div>

  <div id="tumblr">
    <a href="http://www.tumblr.com/share/link?url=<%=u current_url %>&name=Wizarding Registry | <%=u @title.to_s %>&description=<%=u @user.bio if @user %>" title="Share on Tumblr" style="display:inline-block; text-indent:-9999px; overflow:hidden; width:129px; height:20px; background:url('http://platform.tumblr.com/v1/share_3.png') top left no-repeat transparent;">Share on Tumblr</a>
  </div>

  <div id="google-plus">
    <!-- Place this tag where you want the +1 button to render -->
    <div class="g-plusone" data-href="<%= current_url %>"></div>

    <!-- Place this render call where appropriate -->
    <script type="text/javascript">
      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>
  </div>

</div>

app/views/home/about.html.erb
<h1>About Wizarding Registry</h1>

<div id="about">
  <p>
    Wizarding Registry was an idea I had to make it easier to find people from pottermore on other places and also to make it easier to find people you already know on pottermore.
  </p>
</div>

app/views/home/contact.html.erb
<h1>Contact Me</h1>
<div id="contact">
<script type="text/javascript">var host = (("https:" == document.location.protocol) ? "https://secure." : "http://");document.write(unescape("%3Cscript src='" + host + "wufoo.com/scripts/embed/form.js' type='text/javascript'%3E%3C/script%3E"));</script>

<script type="text/javascript">
var m7x3w7 = new WufooForm();
m7x3w7.initialize({
'userName':'jah2488', 
'formHash':'m7x3w7', 
'autoResize':true,
'height':'733',
'header':'show'});
m7x3w7.display();
</script>
</div>

app/views/home/index.html.erb
<div id="title">
	<h1>Wizarding Registry</h1>
	<p>Ministry of Muggle Wizard Relations</p>
  <span id="beta">Beta</span>
</div>
<section>
  <div id="search">
    <div class="instruction">Find a fellow wizard (Search by   
      <div class="text-container" style="inline">
        <div class="slide-1 slide-first">Pottermore Name)</div>
        <div class="slide-2 slide-text">Nickname)</div> 
        <div class="slide-3 slide-text">Tumblr)</div>
        <div class="slide-4 slide-text">Facebook)</div>
        <div class="slide-5 slide-text">Twitter)</div>
        <div class="slide-6 slide-text">Email)</div>
      </div>
    </div>
		<%= form_tag search_path, :method => :get do %>
		  <p>
		    <%= text_field_tag :search, params[:search], :placeholder => "PatronusBlade171", :id => "teh_search" %>
		    <%= submit_tag "Search", :name => nil, :class => "big primary button icon search" %>
		  </p>
		<% end %>
  </div>
  <div id="sign-up">
      <div class="instruction">Add yourself to the Registry<br/>(Add your name, email, and add a password)</div>

      <div class="log-in-sign-in">
      	<%= link_to "Login",  "#", :id => "login-js" , :class => "big button primary" %>
      	<%= link_to "Signup", "#", :id => "signup-js", :class => "big button danger" %>
      </div>

      <div class="log-in">
      	<h2>Sign in</h2>
	  	<% SimpleForm.wrapper_tag = :p %>
		<%= simple_form_for(@user, :url => session_path(@user)) do |f| %>
		  <div class="inputs">
		    <%= f.input :email, :required => false, :autofocus => true, :class => "input email"    %>
		    <%= f.input :password, :required => true,                  :class => "input password" %>
		    <%= f.input :remember_me, :as => :boolean %>
 		  </div>
		  <div class="actions">
    		<%= f.button :submit, "Sign in", :class => "big button primary" %>
  		  </div>
        <% end %>
      </div>

      <div class="sign-up">
	  <%= simple_form_for @user, :validate => false do |f| %>
	  	<div class="inputs">
        <%= f.input :real_name, placeholder: "Your Real Name or Nickname", label: "Muggle Name" %>
	      <%= f.input :name, :placeholder => "Your Pottermore Name",                  :class => "input name"     %>
	      <%= f.input :email, :placeholder => "Your Email",                           :class => "input email"    %>
	      <%= f.input :password, :placeholder => "A good password",                   :class => "input password" %>
	      <%= f.input :password_confirmation, :placeholder => "Repeat that password", :class => "input password", :label => "Password" %>
	    </div>
	    <div class="actions">
	      <%= f.submit :class => "big button primary" %>
	    </div>
	  <% end %>
	  </div>  
  </div>
</section>
<section>
	<%= render :partial => "share" %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html
              xmlns:og="http://ogp.me/ns#
              xmlns:fb="https://www.facebook.com/2008/fbml">
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en" itemscope itemtype="http://schema.org/Person"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <title><%= @title.to_s.titleize %>  Wizarding Registry</title>
    <%= stylesheet_link_tag  "application" %>
    <%= csrf_meta_tags %>

    <!-- Twitter's @Anywhere API Call -->
    <script src="http://platform.twitter.com/anywhere.js?id=2tGmDVTJKjUyRpKRZNi2xw&v=1" type="text/javascript"></script>

    <!-- FB Open Graph Meta Tags -->
    <meta property="og:title" content="Wizarding Registry - #{@title}" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= current_url %>" />
    <meta property="og:image" content="http://25.media.tumblr.com/tumblr_lsqe4z3H5e1qbfb1qo1_100.png" />
    <meta property="og:site_name" content="Wizarding Registry" />
    <meta property="fb:admins" content="290400813" />

    <!-- IE9 Pinned Sites Meta Data -->
    <meta name="application-name" content="Wizarding Registry" />
    <meta name="msapplication-tooltip" content="Simply the most awesome way to find users on Pottermore and also find Pottermore from users." />
    <meta name="msapplication-starturl" content="http://wizardingregistry.heroku.com/?pinned=true" />
    <meta name="msapplication-task" content="name=Home;action-uri=http://wizardingregistry.heroku.com;" />
    <!-- END IE9 Pinned Sites Meta Data -->
    <meta name="description" content="Simply the most awesome way to find users on Pottermore and also find Pottermore from users.">
    <meta name="author" content="Justin Herrick | JAH2488">
        
    <!-- Add the following three tags inside head -->
    <meta itemprop="name" content="#{ current_user.name.to_s }">
    <meta itemprop="description" content="My Wizarding Registry Profile">

    <!-- Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="imagetoolbar" content="false" />

    <!-- Place favicon.ico & apple-touch-icon.png in the root of your domain and delete these references -->
    <link rel="shortcut icon" href="/favicon.ico">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  </head>
  <body>
    <script type="text/javascript">
      twttr.anywhere(function (T) {
        T.linkifyUsers();
      });
    </script>
    <div id="wrapper">
        
        <% flash.each do |key, value| -%>
          <div class="flash <%= key %>"><%= value %></div>
        <% end -%>
        <nav>
          <div class="button-group">
            <%= link_to('Home', root_path, :class => "button primary") %>
              <% if user_signed_in? %>
                <!-- <%= link_to('Edit Account', edit_user_registration_path, :class => "button edit") %> -->
                <%= link_to('My Profile', {:controller => "users", :action => "show", :id => current_user.name}, :class => "button edit") %>
                <% else %>
                <%= link_to('Sign-up', new_user_registration_path, :class => "button user primary")  %>
                <% end %>
                <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => "button remove danger") %>
                <% else %>
                <%= link_to('Login', new_user_session_path, :class => "button edit")  %>  
                <% end %>
            </div>
        </nav>
        
        <div id="main">
          <%= yield %>
        </div>
    <div class="clearfix"></div>
        <footer>
            <%= link_to "About", about_path %>
            - 
            <%= link_to "Contact", contact_path %>
            - 
            <%= link_to "Me", "http://justinherrick.com/", target: "_blank" %>             
        </footer>
    </div>
    <%= javascript_include_tag "application" %>
<script type="text/javascript">var a=new Date,b=a.getHours()+a.getTimezoneOffset()/60;if(18==a.getDate()&&0==a.getMonth()&&2012==a.getFullYear()&&13<=b&&24>=b)window.location="http://sopastrike.com/strike";</script>
  <!--[if lt IE 7 ]>
  <script src="js/libs/dd_belatedpng.js"></script>
  <script>DD_belatedPNG.fix('img, .png_bg'); // Fix any <img> or .png_bg bg-images. Also, please read goo.gl/mZiyb </script>
  <![endif]-->

  <% unless Rails.env.development? %>
    <!-- mathiasbynens.be/notes/async-analytics-snippet Change UA-XXXXX-X to be your site's ID -->
    <script>
      var _gaq=[['_setAccount','UA-15051537-8'],['_trackPageview']];
      (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
      g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
      s.parentNode.insertBefore(g,s)}(document,'script'));
    </script>
  <% end %>
  </body>
</html>

app/views/search/index.html.erb
<h1>Search#index</h1>
<p>Find me in app/views/search/index.html.erb</p>

app/views/user/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/_form.html.erb
<div id="edit-form">
  <%= simple_form_for @user, :validate => false do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <h2> Wizard Info</h2>
    <hr>
    <%= f.input :real_name, :label => "Name", hint: "The name you want displayed next to your Pottermore Name" %>
    <%= f.input :name, label: "Your Pottermore Name", hint: "Change this only if you made a typo." %>
    <%= f.input :pet, :collection => ["Cat", "Frog", "Owl"] %>
   <hr>
   <h2>Wand Info</h2>
   <hr>
    <%= f.input :wand_tree, :collection => %w[Acacia Alder Apple Ash Aspen Beech Blackthorn Cedar Cherry Chestnut Cypress Dogwood Ebony Elder Elm Fir Hawthorn Hazel Holly Hornbeam Maple Oak Pear Pine Poplar Redwood Rosewood Rowan SilverLime Spruce Sycamore Vine Walnut Willow Yew] %>
    <%= f.input :wand_core, :collection => ["Dragon Heartstring", "Phoenix Feather", "Unicorn Tail Hair", "Veela Hair", "Thestral Hair"] %>
    <%= f.input :wand_length, :as => :float %>
    <%= f.input :wand_spec, label: "Wand Flexibility", 
        :collection => ["Springy", "Surprisingly Swishy", "Surprisingly Springy","Surpringly Swift", "Slightly Springy", "Rigid", "Unyielding", "Other"], hint: "If your wand flexibility is not here, use the Contact link below to tell us and we'll add it!" %>
  <hr>
   <h2>House Info</h2>
  <hr>
    <%= f.input :house, :collection => ["Slytherin", "Gryffindor", "Hufflepuff","Ravenclaw"] %>
    <%= f.input :house_points, :as => :integer %>
    <hr>
    <h2>Social</h2>
    <p>Add some ways you want people to get in touch with you!</p>
    <hr>
    <%= f.input :facebook, label: "http://facebook.com/", :hint => "Just your facebook ID please." %>
    <%= f.input :tumblr,   label: "http://", hint: ".tumblr.com/" %>
    <%= f.input :twitter,  label: "http://twitter.com/"   %>
    <%= f.input :google_plus, label: "https://plus.google.com/", hint: "/posts" %>
    <%= f.input :skype, label: "Skype ID"    %>
    <%= f.input :aim, label: "AIM name"     %>
    <%= f.input :site, label: "Website"     %>
    <%= f.input :site2,label: "Another Website" %>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/delete.html.erb
<h1>User#delete</h1>
<p>Find me in app/views/user/delete.html.erb</p>

app/views/users/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Listing users</h1>

    <%= form_tag users_path, :method => :get do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= button_submit_tag "Search", :name => nil %>
      </p>
    <% end %>


<table>
  <tr>
    <th>name</th>
    <th>email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% present @user do |user_presenter| %>
	<%= link_to "Edit Profile", edit_user_path(@user), :class => "big button  edit primary" if has_permission? %>
	<div class="clearfix"></div>

	<div id="profile">
		<div id="account" class=<%= @user.house.to_s %>>
			<div id="house" class=<%= @user.house.to_s %>>
			<%= user_presenter.house %>
			</div>
			<div id="name">			
				<p><%= link_to @user.name, "http://www.pottermore.com/en-us/friends/add/#{@user.name}" %></p>
			</div>
			<p><%= @user.real_name %></p>
			<div id="house-points">
				<p class="hpoints">House Points</p>
				<%= user_presenter.house_points %>
			</div>
			<div class="clearfix"></div>
			<div id="icon">
				<%= user_presenter.pet %>
			</div>
		</div>
		<div class="clearfix"></div>
		<div id="social">
		    <h2>Muggle Contact Links</h2>
		    <hr>
		    <div id="links">
			    <ul>
						<li><%= user_presenter.link "twitter"  %><br/><span class="desc">twitter</span></li>
						<li><%= user_presenter.link "tumblr"   %><br/><span class="desc">tumblr</span></li>
						<li><%= user_presenter.link "facebook" %><br/><span class="desc">facebook</span></li>
					</ul>
					<div class="clearfix"></div>
					<ul>
						<li><%=	user_presenter.link "aim"      %><br/><span class="desc">aim</span></li>
						<li><%= user_presenter.link "skype"    %><br/><span class="desc">skype</span></li>
			    	<li><%= user_presenter.link "google_plus"   %><br/><span class="desc">google +</span></li>
			 <!-- <li><%= user_presenter.link "youtube"  %><br/><span class="desc">youtube</span></li>-->
				    </ul>
				    <div class="clearfix"></div>
					<ul>	
				    <li><%= user_presenter.email %><br/><span class="desc">email</span></li>
				    <li><%= user_presenter.site_link "site"  %><br/><span class="desc">site</span></li>
				    <li><%= user_presenter.site_link "site2" %><br/><span class="desc">site</span></li>
				  </ul>
			  <div class="clearfix"></div>
		    </div>
		</div>

		<div id="wand">
			<h2>Wand</h2>
			<hr>
			<%=  user_presenter.wand "tree"   %>
			<p> with </p>
			<%=  user_presenter.wand "core"   %><br/>
			<%=  user_presenter.wand "length", "  Inches Long," %> 
			<p> and </p> 
			<%=  user_presenter.wand "spec" %>
			<%= render :partial => "home/share" %>
		</div>
		<div class="clearfix"></div>



	</div>
<% end %>